package Client.CORBA;

/**
* Server/CORBA/FileShareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Tuesday, November 21, 2023 12:27:15 o'clock PM CST
*/

public final class FileShareHolder implements org.omg.CORBA.portable.Streamable
{
  public FileShare value = null;

  public FileShareHolder ()
  {
  }

  public FileShareHolder (FileShare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileShareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileShareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileShareHelper.type ();
  }

}
