package Helper;


/**
* Helper/FileShare.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 10:17:34 o'clock PM CST
*/

public interface FileShare extends FileShareOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileShare
