package Helper;


/**
* Helper/FileShareHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 10:17:34 o'clock PM CST
*/

abstract public class FileShareHelper
{
  private static String  _id = "IDL:Helper/FileShare:1.0";

  public static void insert (org.omg.CORBA.Any a, Helper.FileShare that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Helper.FileShare extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Helper.FileShareHelper.id (), "FileShare");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Helper.FileShare read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileShareStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Helper.FileShare value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Helper.FileShare narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Helper.FileShare)
      return (Helper.FileShare)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Helper._FileShareStub stub = new Helper._FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Helper.FileShare unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Helper.FileShare)
      return (Helper.FileShare)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Helper._FileShareStub stub = new Helper._FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
