package Helper;


/**
* Helper/FileShareOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 10:17:34 o'clock PM CST
*/

public interface FileShareOperations 
{

  // Operations related to shared files
  void registerFile (String ownerUsername, String fileName);
  void removeFile (String ownerUsername, String fileName);
  String searchFiles (String fileName);
  String getOwner (String fileName);
  boolean downloadFile (String requesterUsername, String fileName, String ownerUsername);

  // Operations related to owners
  void registerOwner (String username, String ipAddress, int port);
  void updateOnlineStatus (String username, boolean isOnline);
} // interface FileShareOperations
