package Helper;


/**
* Helper/FileSharePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 10:17:34 o'clock PM CST
*/

public abstract class FileSharePOA extends org.omg.PortableServer.Servant
 implements Helper.FileShareOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerFile", new java.lang.Integer (0));
    _methods.put ("removeFile", new java.lang.Integer (1));
    _methods.put ("searchFiles", new java.lang.Integer (2));
    _methods.put ("getOwner", new java.lang.Integer (3));
    _methods.put ("downloadFile", new java.lang.Integer (4));
    _methods.put ("registerOwner", new java.lang.Integer (5));
    _methods.put ("updateOnlineStatus", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Operations related to shared files
       case 0:  // Helper/FileShare/registerFile
       {
         String ownerUsername = in.read_string ();
         String fileName = in.read_string ();
         this.registerFile (ownerUsername, fileName);
         out = $rh.createReply();
         break;
       }

       case 1:  // Helper/FileShare/removeFile
       {
         String ownerUsername = in.read_string ();
         String fileName = in.read_string ();
         this.removeFile (ownerUsername, fileName);
         out = $rh.createReply();
         break;
       }

       case 2:  // Helper/FileShare/searchFiles
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.searchFiles (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Helper/FileShare/getOwner
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.getOwner (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Helper/FileShare/downloadFile
       {
         String requesterUsername = in.read_string ();
         String fileName = in.read_string ();
         String ownerUsername = in.read_string ();
         boolean $result = false;
         $result = this.downloadFile (requesterUsername, fileName, ownerUsername);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Operations related to owners
       case 5:  // Helper/FileShare/registerOwner
       {
         String username = in.read_string ();
         String ipAddress = in.read_string ();
         int port = in.read_long ();
         this.registerOwner (username, ipAddress, port);
         out = $rh.createReply();
         break;
       }

       case 6:  // Helper/FileShare/updateOnlineStatus
       {
         String username = in.read_string ();
         boolean isOnline = in.read_boolean ();
         this.updateOnlineStatus (username, isOnline);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Helper/FileShare:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileShare _this() 
  {
    return FileShareHelper.narrow(
    super._this_object());
  }

  public FileShare _this(org.omg.CORBA.ORB orb) 
  {
    return FileShareHelper.narrow(
    super._this_object(orb));
  }


} // class FileSharePOA
