package Helper;

/**
* Helper/FileShareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 10:17:34 o'clock PM CST
*/

public final class FileShareHolder implements org.omg.CORBA.portable.Streamable
{
  public Helper.FileShare value = null;

  public FileShareHolder ()
  {
  }

  public FileShareHolder (Helper.FileShare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Helper.FileShareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Helper.FileShareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Helper.FileShareHelper.type ();
  }

}
