module Server {
  module CORBA {
    interface FileShare {
        string registerFile(in string fileName, in string ipAddress, in long port);
        string cancelSharing(in string fileName, in string ipAddress, in long port);
        string findSharedFiles(in string filename);
        string getSocketAddressById(in long id);
    };

  };

};