package Server.Helper;

/**
* Server/Helper/FileShareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Sunday, November 19, 2023 9:53:04 o'clock PM CST
*/

public final class FileShareHolder implements org.omg.CORBA.portable.Streamable
{
  public Server.Helper.FileShare value = null;

  public FileShareHolder ()
  {
  }

  public FileShareHolder (Server.Helper.FileShare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server.Helper.FileShareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server.Helper.FileShareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server.Helper.FileShareHelper.type ();
  }

}
