package Server.CORBA;


/**
* Server/CORBA/FileShareOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Tuesday, November 21, 2023 12:27:15 o'clock PM CST
*/

public interface FileShareOperations 
{
  String registerFile (String fileName, String ipAddress, int port);
  String cancelSharing (String fileName, String ipAddress, int port);
  String findSharedFiles (String filename);
  String getSocketAddressById (int id);
} // interface FileShareOperations
