package Server.CORBA;


/**
* Server/CORBA/FileShare.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Tuesday, November 21, 2023 12:27:15 o'clock PM CST
*/

public interface FileShare extends FileShareOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileShare
