package Server.CORBA;


/**
* Server/CORBA/FileSharePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Tuesday, November 21, 2023 12:27:15 o'clock PM CST
*/

public abstract class FileSharePOA extends org.omg.PortableServer.Servant
 implements Server.CORBA.FileShareOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerFile", new java.lang.Integer (0));
    _methods.put ("cancelSharing", new java.lang.Integer (1));
    _methods.put ("findSharedFiles", new java.lang.Integer (2));
    _methods.put ("getSocketAddressById", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Server/CORBA/FileShare/registerFile
       {
         String fileName = in.read_string ();
         String ipAddress = in.read_string ();
         int port = in.read_long ();
         String $result = null;
         $result = this.registerFile (fileName, ipAddress, port);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Server/CORBA/FileShare/cancelSharing
       {
         String fileName = in.read_string ();
         String ipAddress = in.read_string ();
         int port = in.read_long ();
         String $result = null;
         $result = this.cancelSharing (fileName, ipAddress, port);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // Server/CORBA/FileShare/findSharedFiles
       {
         String filename = in.read_string ();
         String $result = null;
         $result = this.findSharedFiles (filename);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Server/CORBA/FileShare/getSocketAddressById
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.getSocketAddressById (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Server/CORBA/FileShare:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileShare _this() 
  {
    return FileShareHelper.narrow(
    super._this_object());
  }

  public FileShare _this(org.omg.CORBA.ORB orb) 
  {
    return FileShareHelper.narrow(
    super._this_object(orb));
  }


} // class FileSharePOA
